on:
  push:
    paths:
      - 'VERSION'
    branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read version number
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Read ChangeLog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          "python3 ${GITHUB_WORKSPACE}/.github/get-unreleased-changelog.py" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ steps.getversion.outputs.version }}'
          release_name: Release ${{ steps.getversion.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ env.CHANGELOG }}
